services:
  facial-recognition:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - ./album:/app/album:ro  # Mount album folder as read-only
      - ./uploads:/app/uploads  # Mount uploads folder for temporary files
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s